### PR TITLE
Fix provider reconnect

### LINKED ISSUE #80: Reconnect provider

### PR DESCRIPTION
**Pull request by MakMuftic**
Closes #80

### CODE REVIEW

File: packages/snap/src/polkadot/api.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ let isConnecting: boolean;
 async function initApi(wsRpcUrl: string): Promise<ApiPromise> {
   provider = new WsProvider(wsRpcUrl);
   let api = new ApiPromise({
-    initWasm: false,
+    initWasm: true,
```
Comment (mpetrunic) [inline packages/snap/src/polkadot/api.ts:17]: ?
We ain't suppose to use wasm.

Comment (MakMuftic) [reply packages/snap/src/polkadot/api.ts]: Leftover from testing
